### ISSUE TITLE
String builder might be more efficient here.

### ISSUE THREAD

**Issue by wdipax** [sanjayJ369/webhook-tester#1]
https://github.com/sanjayJ369/webhook-tester/blob/754e70e2918873592784772510a25ed5625f6b86/cli/whcli.go#L76

I suggest to add a [benchmark test](https://pkg.go.dev/testing#hdr-Benchmarks) for this function. You can measure performance for the current version, then change it to use the [strings builder](https://pkg.go.dev/strings#Builder). Then compare the results and decide which is better.

**Comment by sanjayJ369** [comment]
hey, i am using the following function to benchmark, and updated the function to use a string Builder
```
func BenchmarkReadRequest(b *testing.B) {
	// create a new http request
	body := bytes.NewBuffer([]byte("arbitary body for http request"))
	req := httptest.NewRequest(http.MethodPost, "http://benchmark:8080", body)
	fields := []string{"Header", "Method", "Body"}

	for i := 0; i < b.N; i++ {
		cli.ReadRequestFields(fields, *req)
	}
}
```
it looks like there was some improvement, but the benchmark results are a bit inconsistent?, i don't know the reason but i think it has something to do with reflect package i am using in that function,

**Comment by wdipax** [comment]
Optimisation of Go program usually is about finding a balance between CPU utilization and memory usage. Here is a nice article about Go [garbage collector](https://tip.golang.org/doc/gc-guide) that is helpful to understand the dilema.

To address the inconsistency it is a good practice to run benchmark several times and pick the average result. Here is the [benchmarking](https://www.practical-go-lessons.com/chap-34-benchmarks) reference. I think it is worth to compare both the amount of operations and memory usage before making a final decision. Of course for this case the difference is insignificant and such optimisation is unnecessary, but it is a useful skill to learn.

**Comment by sanjayJ369** [comment]
thanks, now i am getting consistent benchmarks if i use benchtime flag alog with go test
here benchmarkReadRequestConcat refers to a function using string concatination 
and benchmarkReadRequets refers to a function using string builder
![image](https://github.com/sanjayJ369/webhook-tester/assets/111266023/a6621403-6a6d-4e87-b5ef-5e19886bc249)
