### ISSUE TITLE
Consider using flags for command line parameters.

### ISSUE THREAD

**Issue by wdipax** [sanjayJ369/webhook-tester#2]
https://github.com/sanjayJ369/webhook-tester/blob/754e70e2918873592784772510a25ed5625f6b86/cmd/client/main.go#L23

It is OK as is, but if you have a plan to add more parameters later, it might be more convenient to use the [flag](https://pkg.go.dev/flag) package here. Also the server part will definetely benefit from it.

**Comment by sanjayJ369** [comment]
i didn't know about flag package, thanks, i refactored the client main.go file to use the flags
```
        port := flag.Int("p", 8888, "./main -p <portnumber>")

	// check if the flag is set
	argSet := false
	flag.Parse()
	flag.Visit(func(f *flag.Flag) {
		if f.Name == "p" {
			argSet = true
		}
	})
	if !argSet {
		log.Fatalln("expected port number, usage ./main -p <port number>")
	}
```

**Comment by wdipax** [comment]
I don't think you need to check the flag, because you set the default value for it. Just declaration of your flags with parsing them should be enough. Then you can use your values. Also I suggest copying a hint from the readme.

```go
	port := flag.Int("p", 5555, "port on which your webhook program is running")
	flag.Parse()
```

Another nice feature of the flag package is it shows a help message.
```shell
$ go run ./cmd/client/main.go -help
Usage of /tmp/go-build1319976481/b001/exe/main:
  -p int
        port on which your webhook program is running (default 5555)
```

**Comment by wdipax** [comment]
Here is the more sophisticated usage of the [flag](https://gobyexample.com/command-line-subcommands) package. Here author declares the flag set explicitly. I personally prefer this setup for large flag sets because it gives an opportunity to test them properly by the go testing framework.

For this particular setup it is an overkill though.
